#!/bin/bash

set -e -x

BUILT_BOX=$PWD/built-box

CONCOURSE_RELEASE_VERSION=$(cat final-release/version)
GARDEN_LINUX_RELEASE_VERSION=$(cat garden-linux-release/version)

cp final-release/*.tgz concourse-lite/concourse.tgz
cp garden-linux-release/*.tgz concourse-lite/garden-linux.tgz

# wire up virtualbox capabilities
function containers_gone_wild() {
  # create vboxdrv device
  mknod -m 0600 /dev/vboxdrv c 10 58
  mknod -m 0666 /dev/vboxdrvu c 10 57
  mknod -m 0600 /dev/vboxnetctl c 10 56
}

containers_gone_wild

# shim these in for garden-systemd (doesn't support ENV rules)
export GOPATH=/opt/local/go
export PATH=/opt/local/bin:/opt/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PACKER_CONFIG=/opt/local/packerconfig

./concourse-lite/bin/build-virtualbox \
  ${CONCOURSE_RELEASE_VERSION} \
  ${GARDEN_LINUX_RELEASE_VERSION}

mv concourse-lite/*.box $BUILT_BOX
