#!/bin/bash

set -e -x

CONCOURSE_RELEASE_VERSION=$(cat final-release/version)
GARDEN_LINUX_RELEASE_VERSION=$(cat garden-linux-release/version)

cp final-release/*.tgz concourse-lite/concourse.tgz
cp garden-linux-release/*.tgz concourse-lite/garden-linux.tgz

./concourse-lite/bin/build-aws \
  ${CONCOURSE_RELEASE_VERSION} \
  ${GARDEN_LINUX_RELEASE_VERSION}
