#!/bin/bash

set -e -u -x

source $(dirname $0)/lib/vbox.sh

BUILT_BOX=$PWD/built-box

CONCOURSE_RELEASE_VERSION=$(cat final-version/version)

cp binaries/concourse_linux_amd64 concourse-lite/concourse_linux_amd64

./concourse-lite/bin/build-virtualbox ${CONCOURSE_RELEASE_VERSION}

mv concourse-lite/*.box $BUILT_BOX
