#!/bin/bash

set -e -u -x

vagrant init concourse-lite ./built-box/*.box
vagrant up

cd concourse/src/github.com/concourse/testflight

export ATC_URL=http://192.168.100.4:8080

xvfb-run ginkgo -r -race
