#!/bin/bash

set -e -u -x

# wire up VirtualBox devices
# make sure these device numbers match the host!
mknod -m 0600 /dev/vboxdrv c 10 58
mknod -m 0666 /dev/vboxdrvu c 10 57
mknod -m 0600 /dev/vboxnetctl c 10 56

vagrant init concourse-lite ./virtualbox-box/*.box
vagrant up

cd concourse/

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd src/github.com/concourse/testflight

export ATC_URL=http://192.168.100.4:8080

xvfb-run ginkgo -r -race
